server:
  port: 4000

spring:
  data:
    mongodb:
      uri: mongodb+srv://bharat:test1234@mongotestserver.02gzgwo.mongodb.net/
      database: userServiceDB
  datasource:
    url: jdbc:mysql://localhost:3306/java
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test123

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
