server:
  port: 4000

spring:
  data:
    mongodb:
      uri: mongodb+srv://bharat:test1234@mongotestserver.02gzgwo.mongodb.net/
      database: userServiceDB
  datasource:
    url: jdbc:mysql://localhost:3306/java
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test123

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        eventConsumerBufferSize: 10
        waitDurationInOpenState: 3s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      search-cb:
        baseConfig: default
        registerHealthIndicator: true #we can't put this in the default config :(
      details-cb:
        baseConfig: default
        registerHealthIndicator: true
      topAiring-cb:
        baseConfig: default
        registerHealthIndicator: true
      genre-cb:
        baseConfig: default
        registerHealthIndicator: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health, circuitbreakerevents

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /anime-docs
    default-models-expand-depth: -1
    disable-swagger-default-url: true
    syntax-highlight:
      theme: monokai
      activated: true